// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljwfhubipfeguveuwknn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxqd2ZodWJpcGZlZ3V2ZXV3a25uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNjA5OTksImV4cCI6MjA1NTkzNjk5OX0.qv0rI3bkIFP9Rw0c7W0USD5ITSxXMqCECwnw22z6FfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);